### ISSUE TITLE
For OS X homebrew users: sudo not required

### ISSUE THREAD

**Issue by tony** [getantibody/installer#3]
On OS X with homebrew, `/usr/local/bin/` doesn't require superuser. No need for `sudo`.

https://github.com/getantibody/installer/blob/e23eaf178d4c9821f57e8f29256be47761d3a119/install#L30

This could be an issue if there was ever a future homebrew package for antibody.

On homebrew systems, you can also fix this via `sudo chown -R $(whoami) /usr/local/bin/antibody` if it's already been done.

**Comment by rspeed** [comment]
I would think that someone who uses Homebrew would also use it to install Antibody.

**Comment by caarlos0** [comment]
should be fixed on b06e4a8dace1bf0b95f1b041ecc8a0f6f95acb3a
